#!/bin/sh

# THESE VARIABLES HAVE TO BE SET:
ROOT=${UPLUGSHARE}/ext/tree-tagger
BIN=$ROOT/bin
CMD=$ROOT/cmd
LIB=$ROOT/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/tokenize.pl
ABBR_LIST=${LIB}/slovak-abbreviations
PARFILE=${LIB}/slovak.par

if [ -e $ABBR_LIST ]; then 
  $TOKENIZER -a $ABBR_LIST $* |
  $TAGGER $OPTIONS $PARFILE
else
  $TOKENIZER $* |
  $TAGGER $OPTIONS $PARFILE
fi

