#!/bin/sh

# THESE VARIABLES HAVE TO BE SET:
ROOT=${UPLUGSHARE}/ext/tree-tagger
BIN=$ROOT/bin
CMD=$ROOT/cmd
LIB=$ROOT/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/utf8-tokenize.perl
MWL=${CMD}/mwl-lookup.perl
ABBR_LIST=${LIB}/estonian-abbreviations-utf8
PARFILE=${LIB}/estonian-utf8.par
MWLFILE=${LIB}/estonian-mwls-utf8

$TOKENIZER -a $ABBR_LIST $* |
$MWL -f $MWLFILE |
$TAGGER $OPTIONS $PARFILE

