#!/bin/sh

ROOT=${UPLUGSHARE}/ext/tree-tagger
BIN=$ROOT/bin
CMD=$ROOT/cmd
LIB=$ROOT/lib


OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
# TOKENIZER=${CMD}/tokenize.pl
TOKENIZER=${CMD}/utf8-tokenize.perl
ABBR_LIST=${LIB}/french-abbreviations-utf8
PARFILE=${LIB}/french-utf8.par

$TOKENIZER -f -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE


