#!/bin/sh
 
USAGE="grokling <grammarfile>"

PROJECT_HOME=$GROK_HOME
JAVA=java
MAINFILE=SimplePipe

while getopts h:d c
do
     case $c in
     \?) echo $USAGE
         exit 2;;
     esac
done
shift `expr $OPTIND - 1`
 
JARS=`echo ${PROJECT_HOME}/lib/*.jar | tr ' ' ':'`
CP=.:${PROJECT_HOME}/output/classes:${PROJECT_HOME}/src/java:$JARS

echo 'Compiling class files...'
javac -classpath $CP *.java

echo 'Running pipeline...'
echo
$JAVA -mx128m -cp $CP $MAINFILE $@
