#!/bin/bash



JAVA_HOME='/usr/java/j2re1.4.2';

# openNLP
# and Grok

GROK_HOME=${UPLUGHOME}/ext/grok/
JARS=`echo ${GROK_HOME}/lib/*.jar | tr ' ' ':'`
CLASSPATH=${CLASSPATH}:.:${JARS}:${GROK_HOME}/output/classes:${GROK_HOME}/src/java/

DIR=`pwd`;
CHUNKERDIR=${UPLUGHOME}/ext/chunker;
cd ${CHUNKERDIR};


${JAVA_HOME}/bin/java GrokChunkerEN $1


cd ${DIR};

