#!/usr/bin/perl
# -*-perl-*-
#
#---------------------------------------------------------------------------
# Copyright (C) 2004 Jörg Tiedemann
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#---------------------------------------------------------------------------
#
# $Author$
# $Id$
#
# usage: uplug config-file [PARAMETERS]
#
#    config-file ........ a valid Uplug config file (a module)
#    PARAMETERS ......... paremeters for the selected module
#
# if the config-file is not in the current directory the script will
#     - look first in ENV{UPLUGHOME}/systems
#     - then look in  ENV{UPLUGHOME}
#
# example: (run module UPLUGHOME/systems/pre/basic)
#
#     uplug pre/basic -in 1988en.txt -ci 'iso-8859-1' -out 1988en.xml

use strict;
use FindBin qw($Bin);
use lib "$Bin/lib";
use Uplug;

$ENV{UPLUGHOME}=$Bin;


my $uplug=Uplug->new(@ARGV);   # create a new uplug module
$uplug->load();                # load it
$uplug->run();                 # and run it

