#!/usr/bin/perl

use FindBin qw($Bin);
my $HUNPOS=$Bin.'/../hunpos/hunpos-tag';
my $MODEL=$Bin.'/../hunpos/models/se_Suc2x.model';

# system ($HUNPOS,$MODEL,@ARGV);

# hunpos needs piped input from STDIN!
system "$HUNPOS $MODEL < $ARGV[0]";

