#!/usr/bin/perl

use FindBin qw($Bin);

my $JAVA="$ENV{JAVA_HOME}/bin/java";
my $GROK_HOME="$Bin/../grok/";
my $JARS=`echo ${GROK_HOME}/lib/*.jar | tr ' ' ':'`;
$ENV{CLASSPATH}="$ENV{CLASSPATH}:.:${JARS}:${GROK_HOME}/output/classes:${GROK_HOME}/src/java/";


my $DIR=$ENV{PWD};                                  # save current dir
chdir $Bin;                                         # go to Bin
my $file=$ARGV[0];                                  # file to be tagged
if (not -e $file){$file="$DIR/$file";}              # change path if necessary

system "$JAVA GrokTaggerSV $file";                  # call the tagger

chdir $DIR;                                         # go bach to original dir
exit;

