#!/bin/bash


# BIN=/home/staff/joerg/jobb/InWork/tagging/TNT
# TNT=${BIN}/tnt
# MODEL=${BIN}/helasucd-tnt

BIN=/local/ling/tnt/tnt
TNT=${BIN}/tnt
MODEL=${BIN}/models/helasucd-tnt

${TNT} ${MODEL} $1

