#!/bin/sh

# Set these paths appropriately
# ROOT=/home/staff/ljo/etap/taggare
ROOT=/users1/tiedeman/wordalign/TreeTagger
BIN=$ROOT/bin
CMD=$ROOT/cmd
LIB=$ROOT/lib

TOKENIZER=${BIN}/separate-punctuation
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/german-abbreviations
PARFILE=${LIB}/german.par
FILTER=${CMD}/filter-german-tags

# put all on one line
cat $* |
# do tokenization
$TOKENIZER +1 +s +l $ABBR_LIST |
# remove empty lines
grep -v '^$' |
# tagging
$TAGGER $PARFILE -token -lemma -sgml | 
# error correction
$FILTER

