#!/usr/bin/env perl
#-*-perl-*-

use FindBin qw/$Bin/;
use lib "$Bin/../../lib";
use Uplug::Config;

my $SVMTOOL = &find_executable('SVMTagger.pl');
my $MODEL   = &shared_lang().'/svmtool/models/es/cs/Ancora_es';

die "svmtool: no input found!" unless ($ARGV[0]);

system "$SVMTOOL $MODEL < $ARGV[0]";

