#!/usr/bin/perl
#----------------------------------------------------------------------------
# -*-perl-*-
#
# Copyright (C) 2004 Jörg Tiedemann  <joerg@stp.ling.uu.se>
#
# $Id$
#
# this is nothing else than a call to declclue 
# with specific arguments for converting GIZA word alignments to uplug clues!
#
# usage: giza2clue giza.actual
#
# this OVERWRITES 'giza.dbm' and 'giza.dbm.head' in the current directory!!!!
#
#


use strict;
use FindBin qw($Bin);
use lib "$Bin/..";
use Uplug::Align::Word::Giza;
use File::Basename;

my $inverse=0;
my $output='giza.dbm';

my $dir=shift(@ARGV);
if (not -d $dir){$dir=dirname($dir);}
if (@ARGV){$output=shift(@ARGV);}


&Giza2Clue($dir,
	   {},
	   $inverse,{format=>'dbm',
		     file=>$output,
		     'key' => ['source','target'],
		     write_mode=>'overwrite'});



#my $convert="$Bin/declclue -p -o giza.dbm -d ' ' -c 'target,source,value'";
#my $input=$ARGV[0];
#
#system "$convert <$input";
