#!/usr/bin/perl
#----------------------------------------------------------------------------
# -*-perl-*-
#
# Copyright (C) 2004 Jörg Tiedemann  <joerg@stp.ling.uu.se>
#
# $Id$
#
# this is nothing else than a call to declclue 
# with specific arguments for converting GIZA word alignments to uplug clues!
#
# usage: giza2clue giza.actual
#
# this OVERWRITES 'giza.dbm' and 'giza.dbm.head' in the current directory!!!!
#
#


use strict;
use FindBin qw($Bin);

my $convert="$Bin/declclue -p -o giza.dbm -d ' ' -c 'target,source,value'";
my $input=$ARGV[0];

system "$convert <$input";
